import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('mobile diagnostics keeps replay distinct, rejects calibration and clears stopped values', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/gamexr/?diagnostics=1')
  const panel = page.getByRole('dialog', { name: 'USB diagnostics' })
  await expect(panel).toBeVisible()
  await expect(panel.getByText('RECORDED REPLAY', { exact: true })).toBeVisible()
  await panel.getByRole('button', { name: 'Start capture', exact: true }).click()
  await expect(panel.locator('#diag-accel')).toHaveText('0.100 / 0.200 / 9.800')
  await expect(panel.locator('#diag-battery')).toHaveText('—')
  await expect(panel.locator('#diag-battery-status')).toContainText('KIV')
  await panel.getByText('IMU calibration', { exact: true }).click()
  await panel.getByLabel('The board is stationary on a stable surface.').check()
  await panel.getByRole('button', { name: 'Measure gyro bias · 20 seconds' }).click()
  await expect(panel.locator('#diag-calibration-status')).toHaveText('Calibration requires fresh live USB data.')
  const download = page.waitForEvent('download')
  await panel.getByRole('button', { name: 'Export session' }).click()
  const downloaded = await download
  const record = JSON.parse(await readFile((await downloaded.path())!, 'utf8'))
  expect(record.actuationAvailable).toBe(false)
  expect(record.batteryCalibration).toBe('KIV')
  expect(record.records.length).toBeGreaterThan(0)
  expect(record.records.every((entry: {source: string}) => entry.source === 'replay')).toBe(true)
  const initialSession = record.records[0].session
  await panel.getByRole('button', { name: 'Stop', exact: true }).click()
  await expect(panel.locator('#diag-accel')).toHaveText('—')
  await expect(panel.locator('#diag-tilt')).toHaveText('Unavailable')
  await panel.getByRole('button', { name: 'Reconnect bridge', exact: true }).click()
  await expect(panel.getByRole('button', { name: 'Start capture', exact: true })).toBeEnabled()
  await panel.getByRole('button', { name: 'Start capture', exact: true }).click()
  await expect(panel.locator('#diag-accel')).toHaveText('0.100 / 0.200 / 9.800')
  const nextDownload = page.waitForEvent('download')
  await panel.getByRole('button', { name: 'Export session' }).click()
  const next = JSON.parse(await readFile((await (await nextDownload).path())!, 'utf8'))
  expect(next.records.at(-1).session).not.toBe(initialSession)
  expect(await panel.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: test.info().outputPath('diagnostics-mobile.png') })
  await panel.getByRole('button', { name: 'Close diagnostics' }).click()
  await expect(panel).not.toBeVisible()
  expect(errors).toEqual([])
})
